# Generated by Django 3.1.5 on 2021-01-20 15:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'блок 1.0: Слайдер', 'verbose_name_plural': 'блок 1.0: Слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'статус заказа', 'verbose_name_plural': 'статусы заказа'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='comments',
            field=models.TextField(blank=True, verbose_name='комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='shop.ProductCart', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.status', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='общая сумма'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='commercialvehicles',
            name='classification',
            field=models.CharField(blank=True, max_length=200, verbose_name='классификация продукта'),
        ),
        migrations.AlterField(
            model_name='commercialvehicles',
            name='composition',
            field=models.CharField(blank=True, max_length=200, verbose_name='состав продукта'),
        ),
        migrations.AlterField(
            model_name='commercialvehicles',
            name='manufacturer_approval',
            field=models.CharField(blank=True, max_length=200, verbose_name='одобрение производителей'),
        ),
        migrations.AlterField(
            model_name='commercialvehicles',
            name='product_group',
            field=models.CharField(max_length=200, verbose_name='группа продукта'),
        ),
        migrations.AlterField(
            model_name='commercialvehicles',
            name='viscosity',
            field=models.CharField(max_length=6, verbose_name='вязкость продукта'),
        ),
        migrations.AlterField(
            model_name='commercialvehicles',
            name='volume',
            field=models.CharField(blank=True, max_length=6, verbose_name='объем'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='lightmotor',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='lightmotor',
            name='classification',
            field=models.CharField(blank=True, max_length=200, verbose_name='классификация продукта'),
        ),
        migrations.AlterField(
            model_name='lightmotor',
            name='composition',
            field=models.CharField(blank=True, max_length=200, verbose_name='состав продукта'),
        ),
        migrations.AlterField(
            model_name='lightmotor',
            name='manufacturer_approval',
            field=models.CharField(blank=True, max_length=200, verbose_name='одобрение производителей'),
        ),
        migrations.AlterField(
            model_name='lightmotor',
            name='product_group',
            field=models.CharField(max_length=200, verbose_name='группа продукта'),
        ),
        migrations.AlterField(
            model_name='lightmotor',
            name='under_a_specific_brand',
            field=models.BooleanField(default=False, verbose_name='под конкретную модель'),
        ),
        migrations.AlterField(
            model_name='lightmotor',
            name='viscosity',
            field=models.CharField(max_length=6, verbose_name='вязкость продукта'),
        ),
        migrations.AlterField(
            model_name='lightmotor',
            name='volume',
            field=models.CharField(blank=True, max_length=6, verbose_name='объем'),
        ),
        migrations.AlterField(
            model_name='lightmotor',
            name='year_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='год выпуска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='в наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='категория транспорта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(db_index=True, max_length=6, unique=True, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='shop.cart', verbose_name='корзина'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='общая сумма'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='покупатель'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(blank=True, error_messages={'max_length': 'Очень большая длина'}, help_text='до 150 символов, заполнять необязательно', max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='текст под заголовком'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Очень большая длина'}, help_text='просто название слайда до 100 символов, оно обязательно', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='название слайда'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide_img',
            field=models.ImageField(help_text='изображение обрежется до 1920x1024px', upload_to='slider/', verbose_name='добавить изображение'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, error_messages={'max_length': 'Очень большая длина'}, help_text='до 150 символов, заполнять необязательно', max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='заголовок на слайде'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='статус заказа'),
        ),
    ]
