# Generated by Django 3.1.5 on 2021-01-26 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210125_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('phone', models.CharField(max_length=13, verbose_name='номер телефона')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='адрес доставки')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен')], default='new', max_length=100, verbose_name='статус заказа')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='тип заказа')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='дата создания заказа')),
                ('order_data', models.DateField(default=django.utils.timezone.now, verbose_name='дата получения заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='shop.customer', verbose_name='покупатель')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='shop.Order', verbose_name='заказы покупателя'),
        ),
    ]
